# TravisCI configuration for mralaminahamed/phpstan-squad-modules-lite-stubs

language: "php"
os:
  - "linux"
dist: "bionic"

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - "8.1"
  - "8.0"
  - "7.4"

before_install:
  - "phpenv config-rm xdebug.ini"
  - "composer validate --strict"

install:
  - "composer update --no-interaction"
  ## Reinstall sub-packages into /packages/
  #- "composer update --no-interaction"
  - |
    LATEST="$(jq -r '."require"."squad-modules/squad-modules-for-divi"' source/composer.json)"
    wget -P source/ "https://downloads.wordpress.org/plugin/squad-modules-for-divi.${LATEST}.zip"
    unzip -q -d source/ "source/squad-modules-for-divi.${LATEST}.zip"

before_script:
  - "cat ./source/squad-modules-for-divi/squad-modules-for-divi.php"

script:
  - "bash -x ./generate.sh"
  - "php -l squad-modules-lite-constants-stubs.php"
  - "php -l squad-modules-lite-stubs.php"
  - "git diff --exit-code"
  - |
    php -r 'require "vendor/php-stubs/wordpress-stubs/wordpress-stubs.php"; require "squad-modules-lite-constants-stubs.php"; require "squad-modules-lite-stubs.php";'
